version: '3.3'

services:
  ridejournaldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ridejournaldata:/var/lib/mysql
    container_name: ride-journal-server-db

  server:
    image: ridejournalserver-app:latest
    restart: always
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=ridejournaldb
      - DB_PORT=${DB_PORT}
      - DB_SSL=${DB_SSL}
      - BASE_URL=${SERVER_URL}
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - '3000:3000'
    depends_on:
      ridejournaldb:
        condition: service_started
    volumes:
      - serverimages:/app/public/images
    container_name: ride-journal-server-app

volumes:
  ridejournaldata:
  serverimages:
